Update NavBar.tsx
Solución a problemas de despliegue por linting en linea:

17:45:44.735 src/pages/asd.tsx(487,14): error TS2741: Property 'onShowTutorial' is missing in type '{ unseenCount: number; onShowNotifications: (e: MouseEvent<Element, MouseEvent>) => void; }' but required in type 'NavBarProps'.
17:45:44.736 src/pages/repotesAUX.tsx(425,14): error TS2741: Property 'onShowTutorial' is missing in type '{ unseenCount: number; onShowNotifications: (e: MouseEvent<Element, MouseEvent>) => void; }' but required in type 'NavBarProps'.